import '../bind/language_binding.dart';
import '../views/language/screen/language_screen.dart';
import '../bind/about_binding.dart';
import '../views/about/screen/about_screen.dart';
import '../bind/security_binding.dart';
import '../views/security/screen/security_screen.dart';
import '../bind/health_condition_binding.dart';
import '../views/health_condition/screen/health_condition_screen.dart';
import '../bind/goal_screen_binding.dart';
import '../views/goal_screen/screen/goal_screen_screen.dart';
import '../bind/update_profile_binding.dart';
import '../views/update_profile/screen/update_profile_screen.dart';
import '../bind/ai_chat_binding.dart';
import '../views/ai_chat/screen/ai_chat_screen.dart';
import '../bind/nutrition_binding.dart';
import '../views/nutrition/screen/nutrition_screen.dart';
import '../bind/activity_binding.dart';
import '../views/activity/screen/activity_screen.dart';
import '../bind/hydration_binding.dart';
import '../views/hydration/screen/hydration_screen.dart';
import '../bind/sleep_binding.dart';
import '../views/sleep/screen/sleep_screen.dart';
import '../bind/notification_binding.dart';
import '../views/notification/screen/notification_screen.dart';
import '../bind/setting_binding.dart';
import '../views/setting/screen/setting_screen.dart';
import '../bind/blyn_binding.dart';
import '../views/blyn/screen/blyn_screen.dart';
import '../bind/check_binding.dart';
import '../views/check/screen/check_screen.dart';
import '../bind/home_binding.dart';
import '../views/home/screen/home_screen.dart';
import '../bind/profile_setup_binding.dart';
import '../views/profile_setup/screen/profile_setup_screen.dart';
import '../bind/verification_binding.dart';
import '../views/verification/screen/verification_screen.dart';
import '../bind/confirm_binding.dart';
import '../views/confirm/screen/confirm_screen.dart';
import '../bind/reset_password_binding.dart';
import '../views/reset_password/screen/reset_password_screen.dart';
import '../bind/otp_binding.dart';
import '../views/otp/screen/otp_screen.dart';
import '../bind/support_binding.dart';
import '../views/support/screen/support_screen.dart';
import '../bind/questions_binding.dart';
import '../views/questions/screen/questions_screen.dart';
import '../bind/forgot_password_binding.dart';
import '../views/forgot_password/screen/forgot_password_screen.dart';
import '../bind/register_binding.dart';
import '../views/register/screen/register_screen.dart';
import '../bind/welcome_binding.dart';
import '../views/welcome/screen/welcome_screen.dart';
import '../bind/navigation_binding.dart';
import '../views/navigation/screen/navigation_screen.dart';
import '../bind/login_binding.dart';
import '../views/login/screen/login_screen.dart';
import '../bind/splash_binding.dart';
import '../views/splash/screen/splash_screen.dart';
import 'package:get/get_navigation/src/routes/get_route.dart';
part 'pages.dart';

class Routes {
  static var list = RoutePageList.list;
static const languageScreen = '/languageScreen';
static const aboutScreen = '/aboutScreen';
static const securityScreen = '/securityScreen';
static const health_conditionScreen = '/health_conditionScreen';
static const goal_screenScreen = '/goal_screenScreen';
static const update_profileScreen = '/update_profileScreen';
static const ai_chatScreen = '/ai_chatScreen';
static const nutritionScreen = '/nutritionScreen';
static const activityScreen = '/activityScreen';
static const hydrationScreen = '/hydrationScreen';
static const sleepScreen = '/sleepScreen';
static const notificationScreen = '/notificationScreen';
static const settingScreen = '/settingScreen';
static const blynScreen = '/blynScreen';
static const checkScreen = '/checkScreen';
static const homeScreen = '/homeScreen';
static const profile_setupScreen = '/profile_setupScreen';
static const verificationScreen = '/verificationScreen';
static const confirmScreen = '/confirmScreen';
static const reset_passwordScreen = '/reset_passwordScreen';
static const otpScreen = '/otpScreen';
static const supportScreen = '/supportScreen';
static const questionsScreen = '/questionsScreen';
static const forgot_passwordScreen = '/forgot_passwordScreen';
static const registerScreen = '/registerScreen';
static const welcomeScreen = '/welcomeScreen';
static const navigationScreen = '/navigationScreen';
static const loginScreen = '/loginScreen';
static const splashScreen = '/splashScreen';

}
